### ISSUE TITLE
all lights are switched on when putting 1 on

### ISSUE THREAD

**Issue by charlez79** [En3rGy/14100_Hue#29]
When i put 1 light on, the other that is in the same group does the same after 1 sec. I'm not using the group id.
When i put the same light out, the other stays on.
Changing the color does not have the same issue. Only the put on is responding to that command.

**Comment by En3rGy** [comment]
I can not reproduce that behaviour. Can you give more insight? Is this still an issue with the current version?

**Comment by charlez79** [comment]
Hi, you can close this topic. After rebooting the bridge the issue went away. Don't know what caused this in the fist place.

**Comment by charlez79** [comment]
Running the latest version.
Today the issue is back, will try to do some network tracing one of the days
Could you re-open the issue?

**Comment by charlez79** [comment]
I think the problem is related to the feedback. 
Central addresses made 2nd device turn on, removed those now.
Now only feedback is wrong.

`<HTML>
<BODY>
<TABLE><TR><TD>#</TD><TD>Time</TD><TD>Service</TD><TD>Flags </TD><TD>Prio</TD><TD>Source Address</TD><TD>Source Name</TD><TD>Destination Address</TD><TD>Destination Name</TD><TD>Hop Count</TD><TD>Type</TD><TD>DPT</TD><TD>Info</TD></TR><TR><TD>60</TD><TD>7/09/2023&#160;20:21:05,059</TD><TD>from bus</TD><TD></TD><TD>Low</TD><TD>1.1.65</TD><TD>Tastsensor 3 comfort viervoudig F100</TD><TD>0/1/30</TD><TD>Licht Master Bedroom Bed Rechts Schakelen</TD><TD>6</TD><TD>GroupValue_Write</TD><TD>&nbsp;</TD><TD>$01 | On</TD></TR><TR><TD>61</TD><TD>7/09/2023&#160;20:21:05,466</TD><TD>from bus</TD><TD></TD><TD>High</TD><TD>1.5.1</TD><TD>Gira Homeserver</TD><TD>0/1/33</TD><TD>Licht Master Bedroom Bed Rechts Feedback Schakel</TD><TD>5</TD><TD>GroupValue_Write</TD><TD>&nbsp;</TD><TD>$01 | On</TD></TR><TR><TD>66</TD><TD>7/09/2023&#160;20:21:06,394</TD><TD>from bus</TD><TD></TD><TD>High</TD><TD>1.5.1</TD><TD>Gira Homeserver</TD><TD>0/1/23</TD><TD>Licht Master Bedroom Bed Links Feedback Schakel</TD><TD>5</TD><TD>GroupValue_Write</TD><TD>&nbsp;</TD><TD>$01 | On</TD></TR><TR><TD>68</TD><TD>7/09/2023&#160;20:21:06,449</TD><TD>from bus</TD><TD></TD><TD>High</TD><TD>1.5.1</TD><TD>Gira Homeserver</TD><TD>0/1/24</TD><TD>Licht Master Bedroom Bed Links Feedback Helderheid</TD><TD>5</TD><TD>GroupValue_Write</TD><TD>&nbsp;</TD><TD>$3D | 24%</TD></TR><TR><TD>69</TD><TD>7/09/2023&#160;20:21:06,556</TD><TD>from bus</TD><TD></TD><TD>High</TD><TD>1.5.1</TD><TD>Gira Homeserver</TD><TD>0/1/34</TD><TD>Licht Master Bedroom Bed Rechts Feedback Helderhei</TD><TD>5</TD><TD>GroupValue_Write</TD><TD>&nbsp;</TD><TD>$3D | 24%</TD></TR></TABLE>

</BODY>
</HTML>`


Address 0/1/23 is feedback of 2nd device that is reporting ON while no command is given.

Could it be that the status is not filtered to the corresponding configured ID?

**Comment by charlez79** [comment]
In your code you are looking for "on" in data stream to report the status of light/group. 
In my case i'm only turning 1 lamp on.
The group will also report ON since 1 light of 2 in the group is ON. Should there not be a filter that only looks at the lamp status with ID of the lamp in stream instead of all "ON" statuses?

**Comment by En3rGy** [comment]
In line #147 of src/14100_Hue Group (14100).py all IDs not corresponding to the designated item are skipped, so the on check is only performed on those IDs.

But a valid ID is each ID correlating to a specific item. So  e.g. item id, room id, group id ...

I don't know when which id will be triggered by the bridge.

Du you suggest a different behaviour?

**Comment by charlez79** [comment]
I saw that.
I need more insight on what data is sent back.
I'll try to run the simulation one of the days on my pc.
To see what is happening

**Comment by charlez79** [comment]
i'm not able to get the simulator working, getting this error.
Never worked with custom modules

Traceback (most recent call last):
  File "C:\tmp_fw_dir\HSL20_Framework\simulator.py", line 956, in <module>
  File "C:\tmp_fw_dir\HSL20_Framework\simulator.py", line 824, in start
  File "C:\tmp_fw_dir\HSL20_Framework\simulator.py", line 374, in start
  File "C:\tmp_fw_dir\HSL20_Framework\simulator.py", line 428, in _init_logic
  File "<string>", line 1, in <module>
  File "Hue Group (14100)14100", line 464, in <module>
ImportError: No module named hue_lib.hue_item

**Comment by En3rGy** [comment]
Check out the readme.md to get info regarding the development environment. as soon a syou have set this up, you can run the unsit test in the ./tests directory an work with them thesting in your local environment.

**Comment by charlez79** [comment]
Those tests i can run now. But i would like to test the module itself.
Missing singleton module, it's not in the package.

 File "<string>", line 1, in <module>
  File "Hue Group (14100)14100", line 468, in <module>
ImportError: No module named singleton

**Comment by En3rGy** [comment]
added the missing file

**Comment by charlez79** [comment]
still not getting the simulation to work.
  
  File "<string>", line 1, in <module>
  File "Hue Group (14100)14100", line 887, in <module>
  File "Hue Group (14100)14100", line 505, in __init__
NameError: global name 'random' is not defined


this code block is still causing issues, don't know why. When i remove the simulation starts, no errors, but nothing happens...

```
self.logger = logging.getLogger("{}".format(random.randint(0, 9999999)))

        # Create a custom logging level TRACE
        logging.addLevelName(TRACE, "TRACE")

        def trace(self, message, *args, **kws):
            if self.isEnabledFor(TRACE):
                self._log(TRACE, message, args, **kws)

        logging.Logger.trace = trace

        self.bridge = hue_bridge.HueBridge(self.logger)
        self.server = html_server.HtmlServer(self.logger)
        self.singleton = None
        self.eventstream_thread = threading.Thread()  # type: threading.Thread
        self.eventstream_keep_running = threading.Event()
        self.event_list = []
        self.msg_last = str()
        self.curr_bri = 0
        self.g_out_sbc = {}  # type: {int, object}
        self.debug = False  # type: bool

```

**Comment by En3rGy** [comment]
Todo:
- Switch a light in a group via Hue App.
- Record received messages from bridge
- Check code regarding correlation of IDs, or set vs. get

**Comment by En3rGy** [comment]
2x call of switch on / off is triggered by an input on the logic module:

1. https://github.com/En3rGy/14100_Hue/blob/40fdb2e489e0d74eacd7860c815ff4349b2277a0/src/14100_Hue%20Group%20(14100).py#L434
2. https://github.com/En3rGy/14100_Hue/blob/40fdb2e489e0d74eacd7860c815ff4349b2277a0/src/14100_Hue%20Group%20(14100).py#L463

Receiving messages of hue bridge results in https://github.com/En3rGy/14100_Hue/blob/40fdb2e489e0d74eacd7860c815ff4349b2277a0/src/14100_Hue%20Group%20(14100).py#L114 and triggers output signals only. 

**The observed behavior seems to not be the result of the logic module but the surrounding logic.**

**Comment by En3rGy** [comment]
Seems like the light/switch does not turn on but the status output states that the light is on.

**Comment by charlez79** [comment]
Installed v3.10 and fist test seems to fixed the problem. Keep you updated
