### ISSUE TITLE
Feature Request: ability to choose between (0-100%) or (0-255)

### ISSUE THREAD

**Issue by charlez79** [En3rGy/14100_Hue#3]
ability to choose between (0-100%) or (0-255) since the gira color picker is using 0-100%.
I know you can do some calculation, but that makes it more complicated, especially when using the module in scenes.

**Comment by En3rGy** [comment]
fixed in [v1.02](https://github.com/En3rGy/14102_FritzBox_TR-064/releases/tag/v1.02)
