### ISSUE TITLE
Version 1.5 totally not working.

### ISSUE THREAD

**Issue by charlez79** [En3rGy/14100_Hue#6]
expert 4.11
no reaction from lamps, neither groups
Debug page shows this error.
AttributeError: HueGroup_14100_14100 instance has no attribute 'PIN_I_NGROUP'

**Comment by En3rGy** [comment]
V1.5 contained the code from a faulty previos version. This is corrected in v1.6:
https://github.com/En3rGy/14100_Hue/releases/tag/v1.6
